### ISSUE TITLE
Passing extra args to the objective function

### ISSUE THREAD

**Issue by richinex** [rfeinman/pytorch-minimize#12]
Is there a way to pass in extra arguments to the objective function like we have in scipy with the keyword argument args?

**Comment by rfeinman** [comment]
Hi @richinex 

For simplicity of the source code I chose to leave this out because the same behavior is easily obtained using lambda functions and/or functools.partial.

For example

```python
minimize(func, x0, args=(3,))
```

is equivalent to

```python
minimize(lambda x: func(x, 3), x0)
```

**Comment by richinex** [comment]
Ah yes I got it. Gracias.
