### ISSUE TITLE
RuntimeError: ScalarFunction was supplied a function that does not return scalar outputs.

### ISSUE THREAD

**Issue by zanellar** [rfeinman/pytorch-minimize#24]
hi, do you have implemented also the VectorFunction?

**Comment by rfeinman** [comment]
Hi @zanellar - can you explain a bit more what you are trying to do, or perhaps provide a code example?

Most of the tools in this package concern optimizing a scalar function of multiple variables.

**Comment by rfeinman** [comment]
Hi @zanellar - can you explain a bit more what you are trying to do, or perhaps provide a code example?

Most of the tools in this package concern optimizing a scalar function of multiple variables.

**Comment by zanellar** [comment]
I need to find the root of a function from R^n to R^m

**Comment by rfeinman** [comment]
Closing this now that @bhalazs has pointed out the correct solution
