### ISSUE TITLE
Passing args to minimize 

### ISSUE THREAD

**Issue by AhmedThahir** [rfeinman/pytorch-minimize#36]
Hi there.
Great work on this library! 

I would like to know how to pass arguments to the objective function. 

In scipy minimize, we can pass arguments using `args`.

**Comment by AhmedThahir** [comment]
Any updates?

**Comment by rfeinman** [comment]
Hi, I would recommend that you wrap your function using functools.partial if you need to pass additional arguments beyond the parameter being optimized.

**Comment by AhmedThahir** [comment]
Could you give a starter example or share any resources?

**Comment by rfeinman** [comment]
This issue is a duplicate of https://github.com/rfeinman/pytorch-minimize/issues/12

Please see the thread there for suggestions

**Comment by AhmedThahir** [comment]
Thanks!
